### ISSUE TITLE
Can u add custom domain?

### ISSUE THREAD

**Issue by 1337vida** [KennethGomez/LiveShot#3]
Can u add a custom domain for this?

**Comment by KennethGomez** [comment]
Custom domain to upload images? Or just LiveShot domain?

Sorry taking days to answer

**Comment by 1337vida** [comment]
Yes, custom domain to upload images. For example, ShareX allows for custom config import, which specifies to which URL it is uploaded, and it looks like this: 
`
{
	"Version": "13.1.0",
	"Name": "configname",
	"DestinationType": "ImageUploader",
	"RequestMethod": "POST",
	"RequestURL": "upload api",
	"Body": "MultipartFormData",
	"Arguments": {
		"key": "upload api key (not needed)"
	},
	"FileFormName": "file",
	"URL": "$json:url$"
}
`

And i think it should be added, because its a great feature and i love Lightshot but it dosent have custom domains ;/

**Comment by KennethGomez** [comment]
Cool!, I will implement this these days, thank you for your feedback 👍🏽

**Comment by KennethGomez** [comment]
Alright, I made a different way to abord this feature, tell me if you expected something else. Thank you 😄

**Comment by 1337vida** [comment]
How do i configure it? I want to try it

**Comment by 1337vida** [comment]
Nevermind, i found and it looks good! But i think you should add arguments to the Multipart body. I will show you when i get on pc.
