### ISSUE TITLE
Remove unnecessary key press to resize things

### ISSUE THREAD

**Issue by remy-burney-pf** [KennethGomez/LiveShot#6]
Following what is on LightShot tool, it would be good if we don't have to use the "Ctrl" or "Shift" key if it's not required. It's adding an extra step that we have to remember and is unnecessary. 

- To resize the window, add ability to directly drag the existing selection to resize
- To change stroke thickness, you should just be able to scroll the mouse wheel only, without pressing the Ctrl key

Less key press is better.

**Comment by KennethGomez** [comment]
Cool, I will be adding both features as well these days, thank you again!
