### ISSUE TITLE
[Feature] Add extra tool shapes (circles, rounded rectangles, polygon, more arrows styles)

### ISSUE THREAD

**Issue by remy-burney-pf** [KennethGomez/LiveShot#8]
Add extra tool shapes.

![image](https://user-images.githubusercontent.com/18563478/112063659-dd1def00-8bb5-11eb-95b6-524c84828a52.png)

- Rounded Rectangle, with ability to change radius based by holding the "Ctrl" key + scroll maybe. Holding "Shift" will make a square.
- Ellipse, with ability to have a circle when holding the Shift key.
- Polygon, with ability to change the number of sides by holding the "Ctrl" key + scroll.
- Different arrow styles, hold left click on the arrow could bring a sub menu with different arrow styles

![image](https://user-images.githubusercontent.com/18563478/112066438-72bb7d80-8bba-11eb-8fa7-b7ed5fe12087.png)

**Comment by KennethGomez** [comment]
Hmm, I dont think this is needed a lot since it's a screenshot application, not a drawing one.
